### ISSUE TITLE
Adding constrant is not idempotent

### ISSUE THREAD

**Issue by xtya** [michaelsogos/pg-diff#19]
In the schema compare, if idempotent = true, when pg-diff creates the query to add a constraint, it creates this command:

` ALTER TABLE IF EXISTS "public". "Account_tax_regulation" ADD CONSTRAINT "uk_4j7hbk7rp1tmvj37ae7gdfl7" UNIQUE (name);`

however, this only verifies that the table exists and not that the constraint exists. so when the script is executed, if the constraint already exists, it fails.

to be able to check existence, there is no "ADD COSTRAINT IF EXISTS" in postgress, therefore it is necessary to resort to the search query.

in order to do this, I will give you an example:

```
DO $$ begin
      IF NOT EXISTS (SELECT constraint_name
                                           FROM information_schema.constraint_column_usage
                                           WHERE table_schema = 'public' 
                                               AND table_name = 'account_tax_regulation' 
                                               AND constraint_name = 'uk_4j7hbk7rp1tmvj37ae7gdfl7') THEN
                       ALTER TABLE IF EXISTS "public". "Account_tax_regulation" ADD CONSTRAINT 
                                            "uk_4j7hbk7rp1tmvj37ae7gdfl7" UNIQUE (name);
      END IF;
END $$;
```

the commands `DO $$` and `END $$;` are necessary in order to run IF STATEMENT in a script

**IMPORTANT NOTE:**
in case you have to look for a foreign key you have to look for it in the external table as a contraint not in the one in which the foreign Key is missing
eg:
```
DO $$ begin
               IF NOT EXISTS (SELECT constraint_name
                                         FROM information_schema.constraint_column_usage
                                       WHERE table_schema = 'public' 
                                           AND table_name = 'base_partner' 
                                           AND constraint_name = 'fk_qlqlr0w9e99cy3fu0y9339rnq') THEN
                         ALTER TABLE IF EXISTS "public". "Sale_sale_order" ADD CONSTRAINT 
                                       "fk_qlqlr0w9e99cy3fu0y9339rnq" FOREIGN KEY (client_partner) 
                                        REFERENCES base_partner (id);
       END IF;
END $$;
```
**base_partner** in this case is the external reference table of the foreign key and the SELECT must be made on that table

best regards
Mattia

**Comment by michaelsogos** [comment]
Hi @xtya ,

I cannot figure out the issue because:
1. If the compared tables have same constraint name and same definition (columns involved), it will not create the statement
2. If the compared tables have same constraint name but different definition, it will DROP constraint and recreate again with the same name
3. If the compared source table has constraint not existing in target table, than it will be created
4. If the compared target table has constraint not existing in source table, than it will be dropped

I need more information about your case, because from internal test it should not be possible.
Anyway, an IF CONSTRAINT EXISTS is not needed because firstly will be dropped and in case created again. Your issue could be that you don't have the DROP CONSTRAINT statement, is this the case?
