### ISSUE TITLE
Pg-diff doesn't detect dropped tables

### ISSUE THREAD

**Issue by viktorsamokov** [michaelsogos/pg-diff#3]
In my development database i dropped some tables that also exist on the "production" database. Then when  running "pg-diff -c development patch_name" it gave empty file. I guess it doesn't detect deleted tables. 

Is there a possibility to have this kind of feature?

**Comment by michaelsogos** [comment]
Hi Viktor,

This feature is under development and will be available in next release.
Keep in mind that it is really dangerous because the actual version of library is not able to recognize an RENAMED object, so just in case the sql patch will DROP a table even if has been just renamed.

However in version 1.3.x will be introduced an advanced tracking system to cover also object renaming, then the DROP statement will be generated only when it is really a DROP.

Get in touch 😄

**Comment by michaelsogos** [comment]
In version 1.2.5 has been added also support for VIEW, MVIEW and FUNCTION
