### ISSUE TITLE
It does not appear that the tool retrieve stored proc differences nor new or dropped one

### ISSUE THREAD

**Issue by bgiavottoatwork** [michaelsogos/pg-diff#35]
hi, Do you plan to implement this?

**Comment by michaelsogos** [comment]
Dear @bgiavottoatwork 

The purpose of this tool is exactly to retrieve NEWER or DIFFERENT object between two databases (functions included).
Actually i tested it again to check if there are unknown bugs, but test passed successfully.
**I need help to reproduce your issue; can you supply me a backup for both database in state you want to compare (even without data of course 😄 )?**

About DROP they are not involved by design, let me explain better:
1. If for any reason a VIEW\FUNCTION\MVIEW\INDEX is different between databases, then the script will create a DROP statement and a CREATE idempotent statement (plus grants and ownership statements)
2. Never the tool will check for MISSING objects from SOURCE DB that still exists on TARGET DB, because it can produce unwanted and dangerous patches. Let's image a situation where the target db contains more object (eg tables) that never will exists on source and instead exists on target for very different reasons (usually a staging database which contains objects created for many different purpose over the time, or like when your target DB contains objects from previous "schema version" that you are not ready to erase 'cause you are still migrating schema on target db). For those and many other reasons, the DROP MISSING OBJECT cannot be the default behaviour!

If you agree i can provide a new config feature to allow DROP of every existing object on TARGET DB that don't match with SOURCE DB. Eventually you will use it at your own risk !!! 😄

**Comment by michaelsogos** [comment]
Dear @bgiavottoatwork 

Sorry for the late time.
I resolved it time ago, from my commit log seems (May 16th, 2020), you have to just set `compareOptions.schemaCompare.dropMissingFunction = true`

Did you tried it ?
Is it working for you?
