### ISSUE TITLE
pg-diff has some difficulty to create the migration file if there are fields with break lines inside (Data compare)

### ISSUE THREAD

**Issue by mattiabettinsoli98** [michaelsogos/pg-diff#8]
If I have fields with break lines inside, every time I create the migration file, pg-diff includes these fields as if there were differences.

MBE

**Comment by michaelsogos** [comment]
@mattiabettinsoli98 

String can be formatted in UNIX (LF) or WINDOWS (CRLF) line break.
Data compare, even if string seems to be the same, evaluate two identical strings as "not equals" if they use different BREAK LINE format.

Based on example you supplied me privately this is the case.
The responsability of pg-diff is to evaluate IDENTICAL fields values in order to assure the perfect replication.

Definetly you have to care about how do you persist multi-line string in your db, and of course how your DB IDE play with strings 😄 .

In my experience, tools like DBEaver change LINE BREAK FORMAT automatically when edit string from visual grid editor.
